Chat Window: Load history, end to end working nostr chat, UI Improvements
lnflash/flash-mobile pull request #102
Opened 2024-03-07 13:42 UTC by abhay-raizada

Make chat work, solvves https://github.com/lnflash/flash-mobile/issues/100

2024-03-11 11:45 UTC, abhay-raizada commented
1. Chat screen now shows nostr users you've previously messaged:
![image](https://github.com/lnflash/flash-mobile/assets/8532031/42875a59-c0c2-4288-8ab3-f9586a54b2b4)

2. Message screen now loads up past messages: 
<img width="407" alt="image" src="https://github.com/lnflash/flash-mobile/assets/8532031/695be060-d1a9-4bc0-aa99-3c9ad51720b6">

3. UI enhancements in the message screen 
4. Made messages fuctional

2024-03-11 13:23 UTC, islandbitcoin commented
Feedback: (see screenshots)

**Chat:**
- on Android, the "no messages here yet" is displaying mirror reversed. on iOS is it not reversed.
- not able to single-click on user to open up chat window, feels like I have to click twice, once to remove the keyboard and then again to open the window.
- I still cannot see the send message button on Android.
- after sending a message, under the message there is a "received message" label. That should be either much smaller compared to the actual note, or it should be hidden
- message are being sent successfully, but no message responses are being received in flash when I get a reply from another nostr client
- on IOS, the chat window gets pushed up to the top of the screen and I cannot see the chat history. everything feels a bit too large. 
- When pressing back and then going into the chat window again, all history is lost. 

**Search:**
- I created two flash users. When typing in the npub from one of those flash users into the search bar, I cannot find the user, I get no results. This might be because the user has not posted anything or finished setting up the profile?

**Pay:**
- pay button does not auto-fill in the lightning address of the recipient when going to the send screen. this should skip the initial send screen and already have the lightning address populated and only ask the user for the amount to send.

Screenshots:
![IMAGE 2024-03-11 09:22:34](https://github.com/lnflash/flash-mobile/assets/34528298/091899e7-ed51-480d-85f0-30820eeb5be6)
![IMAGE 2024-03-11 09:23:12](https://github.com/lnflash/flash-mobile/assets/34528298/02620f48-2f70-430d-9ccf-e2ad941c07ce)
![IMAGE 2024-03-11 09:23:19](https://github.com/lnflash/flash-mobile/assets/34528298/b7841cf0-8266-4d06-b0b8-86fdbf5d1c21)
![IMAGE 2024-03-11 09:23:24](https://github.com/lnflash/flash-mobile/assets/34528298/73ad8be8-eb75-402b-b92e-f291c1fe2f45)

2024-03-11 19:41 UTC, islandbitcoin requested changes

2024-03-11 19:41 UTC, islandbitcoin commented on app/config/galoy-instances.ts
> +    authUrl: "https://api.staging.flashapp.me:8080",
remove port 8080

2024-03-11 19:41 UTC, islandbitcoin commented on app/hooks/use-nostr-profile.ts
> +  const relays = ["wss://relay.damus.io", "wss://relay.primal.net", "wss://nos.lol"]
definitely add 3 or 4 more relays:
wss://purplerelay.com/
wss://relay.snort.social/
wss://nostr.bitcoiner.social/
wss://nostr.oxtr.dev/
wss://relay.mostr.pub/
wss://purplerelay.com

2024-03-14 14:25 UTC, islandbitcoin approved these changes
ACK

2024-03-15 13:13 UTC, merged