Use NIP17 in the mobile client
lnflash/flash-mobile pull request #183
Opened 2024-07-04 14:14 UTC by abhay-raizada

Solves https://github.com/lnflash/flash-mobile/issues/100

2024-08-13 13:24 UTC, abhay-raizada commented
How the chat List screen looks like now: 
<img width="376" alt="image" src="https://github.com/user-attachments/assets/1b9fc57a-0026-442d-abda-8688ddabba73">

2024-08-17 14:54 UTC, islandbitcoin commented
@abhay-raizada looks like this branch has conflicts with `main`

2024-08-20 13:46 UTC, abhay-raizada commented
@islandbitcoin rebased and fixed the conflicts

2024-10-18 18:37 UTC, Nodirbek75 requested changes

2024-10-18 18:37 UTC, Nodirbek75 commented on app/i18n/raw-i18n/source/en.json
> +        "headline": "Produt of Jamaica",
Should be "Product of Jamaica".

2024-10-22 13:46 UTC, abhay-raizada commented on app/i18n/raw-i18n/source/en.json
> +        "headline": "Produt of Jamaica",
oops

2024-10-22 13:47 UTC, abh3po commented on app/i18n/raw-i18n/source/en.json
> +        "headline": "Produt of Jamaica",
must have been a rebase issue, fixed it

2024-10-22 13:56 UTC, Nodirbek75 approved these changes

2024-12-18 21:59 UTC, islandbitcoin commented
@abhay-raizada items to complete before we merge:
- resolve relay slowness
- add beta feature toggle to settings for nostr chat

2025-01-14 11:09 UTC, merged